// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/accesscontrol/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_70bf81890cee44c6, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MessageDependencyMapping struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=cosmos.accesscontrol.v1beta1.MessageType" json:"message_type,omitempty"`
	ModuleName           Module      `protobuf:"varint,2,opt,name=module_name,json=moduleName,proto3,enum=cosmos.accesscontrol.v1beta1.Module" json:"module_name,omitempty"`
	ResourceDependencies []string    `protobuf:"bytes,3,rep,name=resource_dependencies,json=resourceDependencies,proto3" json:"resource_dependencies,omitempty"`
}

func (m *MessageDependencyMapping) Reset()         { *m = MessageDependencyMapping{} }
func (m *MessageDependencyMapping) String() string { return proto.CompactTextString(m) }
func (*MessageDependencyMapping) ProtoMessage()    {}
func (*MessageDependencyMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_70bf81890cee44c6, []int{1}
}
func (m *MessageDependencyMapping) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MessageDependencyMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MessageDependencyMapping.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MessageDependencyMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageDependencyMapping.Merge(m, src)
}
func (m *MessageDependencyMapping) XXX_Size() int {
	return m.Size()
}
func (m *MessageDependencyMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageDependencyMapping.DiscardUnknown(m)
}

var xxx_messageInfo_MessageDependencyMapping proto.InternalMessageInfo

func (m *MessageDependencyMapping) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_ANY_MESSAGE
}

func (m *MessageDependencyMapping) GetModuleName() Module {
	if m != nil {
		return m.ModuleName
	}
	return Module_ANY_MODULE
}

func (m *MessageDependencyMapping) GetResourceDependencies() []string {
	if m != nil {
		return m.ResourceDependencies
	}
	return nil
}

type Params struct {
	// mapping between every message type and its predetermined resource read/write sequence
	MessageDependencyMapping []MessageDependencyMapping `protobuf:"bytes,1,rep,name=message_dependency_mapping,json=messageDependencyMapping,proto3" json:"message_dependency_mapping" yaml:"message_dependency_mapping"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_70bf81890cee44c6, []int{2}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMessageDependencyMapping() []MessageDependencyMapping {
	if m != nil {
		return m.MessageDependencyMapping
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmos.accesscontrol.v1beta1.GenesisState")
	proto.RegisterType((*MessageDependencyMapping)(nil), "cosmos.accesscontrol.v1beta1.MessageDependencyMapping")
	proto.RegisterType((*Params)(nil), "cosmos.accesscontrol.v1beta1.Params")
}

func init() {
	proto.RegisterFile("cosmos/accesscontrol/genesis.proto", fileDescriptor_70bf81890cee44c6)
}

var fileDescriptor_70bf81890cee44c6 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0xae, 0xd2, 0x40,
	0x14, 0xee, 0x08, 0x21, 0x71, 0x4a, 0x5c, 0x34, 0x98, 0x34, 0xc4, 0x14, 0x6c, 0x58, 0xc0, 0xc2,
	0x36, 0x94, 0xc4, 0x05, 0xcb, 0x06, 0xe3, 0x06, 0x8c, 0xa9, 0xae, 0xdc, 0x34, 0xc3, 0xf4, 0xa4,
	0x36, 0x32, 0x33, 0x4d, 0x67, 0x30, 0xf6, 0x2d, 0x5c, 0xba, 0xd3, 0x47, 0xf0, 0x31, 0x58, 0xb2,
	0x74, 0x45, 0x0c, 0xf8, 0x04, 0x3e, 0x81, 0xa1, 0x53, 0xd4, 0xfb, 0x03, 0xf7, 0xae, 0x66, 0x26,
	0xe7, 0xfb, 0x39, 0xdf, 0x99, 0x83, 0x5d, 0x2a, 0x24, 0x13, 0xd2, 0x27, 0x94, 0x82, 0x94, 0x54,
	0x70, 0x55, 0x88, 0x95, 0x9f, 0x02, 0x07, 0x99, 0x49, 0x2f, 0x2f, 0x84, 0x12, 0xd6, 0x13, 0x8d,
	0xf1, 0xae, 0x60, 0xbc, 0x8f, 0xe3, 0x25, 0x28, 0x32, 0xee, 0x76, 0x52, 0x91, 0x8a, 0x0a, 0xe8,
	0x1f, 0x6f, 0x9a, 0xd3, 0x1d, 0xdc, 0xaa, 0x4b, 0x05, 0x97, 0x8a, 0x70, 0x55, 0x2b, 0xbb, 0x11,
	0x6e, 0xbf, 0xd4, 0x56, 0x6f, 0x14, 0x51, 0x60, 0x85, 0xb8, 0x95, 0x93, 0x82, 0x30, 0x69, 0xa3,
	0x3e, 0x1a, 0x9a, 0xc1, 0xc0, 0xbb, 0x64, 0xed, 0xbd, 0xae, 0xb0, 0x61, 0x73, 0xb3, 0xeb, 0x19,
	0x51, 0xcd, 0x74, 0x7f, 0x21, 0x6c, 0x2f, 0x40, 0x4a, 0x92, 0xc2, 0x0c, 0x72, 0xe0, 0x09, 0x70,
	0x5a, 0x2e, 0x48, 0x9e, 0x67, 0x3c, 0xb5, 0xe6, 0xb8, 0xcd, 0x74, 0x2d, 0x56, 0x65, 0x0e, 0x95,
	0xcd, 0xa3, 0x60, 0x74, 0xd9, 0xa6, 0x56, 0x7b, 0x5b, 0xe6, 0x10, 0x99, 0xec, 0xdf, 0xc3, 0x7a,
	0x81, 0x4d, 0x26, 0x92, 0xf5, 0x0a, 0x62, 0x4e, 0x18, 0xd8, 0x0f, 0x2a, 0xb1, 0x3b, 0x7a, 0x5e,
	0x54, 0x84, 0x08, 0x6b, 0xe2, 0x2b, 0xc2, 0xc0, 0x9a, 0xe0, 0xc7, 0x05, 0x48, 0xb1, 0x2e, 0x28,
	0xc4, 0xc9, 0xa9, 0xe5, 0x0c, 0xa4, 0xdd, 0xe8, 0x37, 0x86, 0x0f, 0xa3, 0xce, 0xa9, 0x38, 0xfb,
	0xaf, 0xe6, 0x7e, 0x47, 0xb8, 0xa5, 0xf3, 0x5b, 0x5f, 0x11, 0xee, 0x9e, 0x52, 0xfd, 0xe5, 0x97,
	0x31, 0xd3, 0x99, 0x6d, 0xd4, 0x6f, 0x0c, 0xcd, 0xe0, 0xf9, 0xbd, 0x32, 0xde, 0x98, 0x58, 0x38,
	0x3a, 0x0e, 0xf7, 0xf7, 0xae, 0xf7, 0xb4, 0x24, 0x6c, 0x35, 0x75, 0xcf, 0xfb, 0xb8, 0x91, 0xcd,
	0xce, 0x88, 0x4c, 0x9b, 0x5f, 0xbe, 0xf5, 0x8c, 0x70, 0xbe, 0xd9, 0x3b, 0x68, 0xbb, 0x77, 0xd0,
	0xcf, 0xbd, 0x83, 0x3e, 0x1f, 0x1c, 0x63, 0x7b, 0x70, 0x8c, 0x1f, 0x07, 0xc7, 0x78, 0x17, 0xa4,
	0x99, 0x7a, 0xbf, 0x5e, 0x7a, 0x54, 0x30, 0xbf, 0x5e, 0x1c, 0x7d, 0x3c, 0x93, 0xc9, 0x07, 0xff,
	0xd3, 0xb5, 0x2d, 0x3a, 0xfe, 0x9c, 0x5c, 0xb6, 0xaa, 0x15, 0x9a, 0xfc, 0x09, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0x63, 0x18, 0xf7, 0xc2, 0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MessageDependencyMapping) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MessageDependencyMapping) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MessageDependencyMapping) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResourceDependencies) > 0 {
		for iNdEx := len(m.ResourceDependencies) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ResourceDependencies[iNdEx])
			copy(dAtA[i:], m.ResourceDependencies[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.ResourceDependencies[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ModuleName != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ModuleName))
		i--
		dAtA[i] = 0x10
	}
	if m.MessageType != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MessageType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MessageDependencyMapping) > 0 {
		for iNdEx := len(m.MessageDependencyMapping) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MessageDependencyMapping[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *MessageDependencyMapping) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MessageType != 0 {
		n += 1 + sovGenesis(uint64(m.MessageType))
	}
	if m.ModuleName != 0 {
		n += 1 + sovGenesis(uint64(m.ModuleName))
	}
	if len(m.ResourceDependencies) > 0 {
		for _, s := range m.ResourceDependencies {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MessageDependencyMapping) > 0 {
		for _, e := range m.MessageDependencyMapping {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MessageDependencyMapping) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MessageDependencyMapping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MessageDependencyMapping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageType", wireType)
			}
			m.MessageType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MessageType |= MessageType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModuleName", wireType)
			}
			m.ModuleName = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ModuleName |= Module(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResourceDependencies", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceDependencies = append(m.ResourceDependencies, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageDependencyMapping", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageDependencyMapping = append(m.MessageDependencyMapping, MessageDependencyMapping{})
			if err := m.MessageDependencyMapping[len(m.MessageDependencyMapping)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
