// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/params/types/fees_params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Defines fee params that are controlled through governance
type FeesParams struct {
	GlobalMinimumFees github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=global_minimum_fees,json=globalMinimumFees,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"global_minimum_fees"`
}

func (m *FeesParams) Reset()         { *m = FeesParams{} }
func (m *FeesParams) String() string { return proto.CompactTextString(m) }
func (*FeesParams) ProtoMessage()    {}
func (*FeesParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f69e0057193f3, []int{0}
}
func (m *FeesParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeesParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeesParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeesParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeesParams.Merge(m, src)
}
func (m *FeesParams) XXX_Size() int {
	return m.Size()
}
func (m *FeesParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FeesParams.DiscardUnknown(m)
}

var xxx_messageInfo_FeesParams proto.InternalMessageInfo

func (m *FeesParams) GetGlobalMinimumFees() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.GlobalMinimumFees
	}
	return nil
}

type GenesisState struct {
	FeeParams FeesParams `protobuf:"bytes,1,opt,name=fee_params,json=feeParams,proto3" json:"fee_params"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f9f69e0057193f3, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetFeeParams() FeesParams {
	if m != nil {
		return m.FeeParams
	}
	return FeesParams{}
}

func init() {
	proto.RegisterType((*FeesParams)(nil), "cosmos.params.v1beta1.FeesParams")
	proto.RegisterType((*GenesisState)(nil), "cosmos.params.v1beta1.GenesisState")
}

func init() {
	proto.RegisterFile("cosmos/params/types/fees_params.proto", fileDescriptor_6f9f69e0057193f3)
}

var fileDescriptor_6f9f69e0057193f3 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0xce, 0x2f, 0xce,
	0xcd, 0x2f, 0xd6, 0x2f, 0x48, 0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6,
	0x4f, 0x4b, 0x4d, 0x2d, 0x8e, 0x87, 0x88, 0xe8, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0x89, 0x42,
	0x94, 0xe9, 0x41, 0x05, 0xcb, 0x0c, 0x93, 0x52, 0x4b, 0x12, 0x0d, 0xa5, 0x44, 0xd2, 0xf3, 0xd3,
	0xf3, 0xc1, 0x2a, 0xf4, 0x41, 0x2c, 0x88, 0x62, 0x29, 0x39, 0xa8, 0x99, 0x49, 0x89, 0xc5, 0xa9,
	0xfa, 0x50, 0xa5, 0xfa, 0xc9, 0xf9, 0x99, 0x79, 0x10, 0x79, 0xa5, 0x4e, 0x46, 0x2e, 0x2e, 0xb7,
	0xd4, 0xd4, 0xe2, 0x00, 0xb0, 0x61, 0x42, 0xd5, 0x5c, 0xc2, 0xe9, 0x39, 0xf9, 0x49, 0x89, 0x39,
	0xf1, 0xb9, 0x99, 0x79, 0x99, 0xb9, 0xa5, 0xb9, 0xf1, 0x20, 0xfb, 0x25, 0x18, 0x15, 0x98, 0x35,
	0xb8, 0x8d, 0x24, 0xf5, 0xa0, 0x36, 0x83, 0x0c, 0x83, 0xd9, 0xab, 0xe7, 0x9c, 0x9f, 0x99, 0xe7,
	0x64, 0x70, 0xe2, 0x9e, 0x3c, 0xc3, 0xaa, 0xfb, 0xf2, 0x1a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49,
	0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x50, 0x9b, 0x21, 0x94, 0x6e, 0x71, 0x4a, 0x36, 0xc4, 0x47, 0x60,
	0x0d, 0xc5, 0x41, 0x82, 0x10, 0x7b, 0x7c, 0x21, 0xd6, 0x80, 0x9c, 0xa0, 0x14, 0xc6, 0xc5, 0xe3,
	0x9e, 0x9a, 0x97, 0x5a, 0x9c, 0x59, 0x1c, 0x5c, 0x92, 0x58, 0x92, 0x2a, 0xe4, 0xc6, 0xc5, 0x95,
	0x96, 0x9a, 0x0a, 0xf5, 0xbc, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0xa2, 0x1e, 0x56, 0xdf,
	0xeb, 0x21, 0xfc, 0xe0, 0xc4, 0x02, 0x72, 0x4b, 0x10, 0x67, 0x5a, 0x6a, 0x2a, 0x54, 0xc0, 0x73,
	0xc5, 0x23, 0x39, 0xc6, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92, 0x63, 0x7c, 0xf0, 0x48, 0x8e,
	0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c, 0x96, 0x63, 0x88, 0xd2, 0xc6,
	0xeb, 0xe4, 0x0a, 0x94, 0xd8, 0x48, 0x62, 0x03, 0x87, 0x9a, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x28, 0x4f, 0x78, 0x09, 0xab, 0x01, 0x00, 0x00,
}

func (this *FeesParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeesParams)
	if !ok {
		that2, ok := that.(FeesParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.GlobalMinimumFees) != len(that1.GlobalMinimumFees) {
		return false
	}
	for i := range this.GlobalMinimumFees {
		if !this.GlobalMinimumFees[i].Equal(&that1.GlobalMinimumFees[i]) {
			return false
		}
	}
	return true
}
func (this *GenesisState) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GenesisState)
	if !ok {
		that2, ok := that.(GenesisState)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.FeeParams.Equal(&that1.FeeParams) {
		return false
	}
	return true
}
func (m *FeesParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeesParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeesParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GlobalMinimumFees) > 0 {
		for iNdEx := len(m.GlobalMinimumFees) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GlobalMinimumFees[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFeesParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FeeParams.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintFeesParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintFeesParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovFeesParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeesParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GlobalMinimumFees) > 0 {
		for _, e := range m.GlobalMinimumFees {
			l = e.Size()
			n += 1 + l + sovFeesParams(uint64(l))
		}
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FeeParams.Size()
	n += 1 + l + sovFeesParams(uint64(l))
	return n
}

func sovFeesParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFeesParams(x uint64) (n int) {
	return sovFeesParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeesParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeesParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeesParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeesParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GlobalMinimumFees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeesParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeesParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeesParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GlobalMinimumFees = append(m.GlobalMinimumFees, types.Coin{})
			if err := m.GlobalMinimumFees[len(m.GlobalMinimumFees)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeesParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeesParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeesParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeesParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeesParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFeesParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeesParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFeesParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeesParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeesParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeesParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeesParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFeesParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFeesParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFeesParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFeesParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeesParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFeesParams = fmt.Errorf("proto: unexpected end of group")
)
